services:
  redis:
    image: redis:8.0-M04-alpine
    container_name: redis
    hostname: redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default_network

  # http://localhost:5540
  # add database redis:6379
  redis-insight:
    container_name: redis-insight
    restart: no
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redis-insight-data:/data
    networks:
      - default_network

volumes:
  redis-data:
    name: redis-data
    driver: local

  redis-insight-data:
    name: redis-insight-data
    driver: local

networks:
  default_network:
    driver: bridge