"""Auto-generated migration

Revision ID: 6eb7ddb787df
Revises: add_channel_config_fks
Create Date: 2025-12-25 22:27:49.139747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb7ddb787df'
down_revision: Union[str, None] = 'add_channel_config_fks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_channel_configs_channel_id_channels'), 'channel_configs', type_='foreignkey')
    op.create_foreign_key(None, 'channel_configs', 'channels', ['channel_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_configs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_channel_configs_channel_id_channels'), 'channel_configs', 'channels', ['channel_id'], ['uuid'])
    # ### end Alembic commands ###
