"""Auto-generated migration

Revision ID: 4e5d938d124d
Revises: 293a2a5d3b77
Create Date: 2025-06-21 19:35:02.029673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5d938d124d'
down_revision: Union[str, None] = '293a2a5d3b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('channels', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'updated_at')
    op.drop_column('channels', 'created_at')
    # ### end Alembic commands ###
