"""Add channel config

Revision ID: 2bf89298285e
Revises: facc64635826
Create Date: 2025-12-24 16:59:26.028282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf89298285e'
down_revision: Union[str, None] = 'facc64635826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_post_owner_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_configs')
    # ### end Alembic commands ###
